spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=Sonali@21
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
